lib/chatter_web/router.ex
defmodule ChatterWeb.Router do
  use ChatterWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatterWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatterWeb do
    pipe_through :browser

    get "/", RoomController, :index
    resources("/rooms", RoomController, except: [:index])
    resources("/sessions", SessionController, only: [:new, :create])
    resources("/registrations", RegistrationController, only: [:new, :create])
    delete "/sign_out", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChatterWeb.Telemetry
    end
  end
end

lib/chatter_web/controllers/session_controller.ex
defmodule ChatterWeb.SessionController do
  use ChatterWeb, :controller

  alias Chatter.Accounts

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Accounts.sign_in(email, password) do
      {:ok, user} ->
        conn
        |> put_session(:current_user_id, user.id)
        |> put_flash(:info, "You've signed in")
        |> redirect(to: Routes.room_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "Invalid Email or Password")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Accounts.sign_out()
    |> redirect(to: Routes.room_path(conn, :index))
  end
end

lib/chatter_web/views/session_view.ex
defmodule ChatterWeb.SessionView do
  use ChatterWeb, :view
end

lib/chatter_web/templates/session/new.html.eex
<div class="row">
  <div class="col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-6 offset-xl-3 margin-top-200">
    <%= render ChatterWeb.SharedView, "_alert.html", assigns %>

    <div class="card card__custom">
      <div class="row">
        <div class="col-lg-6 left">
          <div class="logo">
            <img src="/images/chat.png" >
            <h3>ChatApp</h3>
          </div>
          <div class="form form__session">
            <%= form_for @conn, Routes.session_path(@conn, :create), [as: :session, class: "form-signin"], fn f -> %>
              <div class="text-center title">
                <h2>Sign In</h2>
              </div>

              <div class="form-group">
                <%= label f, :email, class: "control-label" %>
                <%= text_input f, :email, class: "form-control", required: true, autofocus: true %>
                <%= error_tag f, :email %>
              </div>
              <div class="form-group">
                <%= label f, :password, class: "control-label" %>
                <%= password_input f, :password, class: "form-control", required: true %>
                <%= error_tag f, :password %>
              </div>

              <%= submit "Sign In", class: "btn btn-purple margin-0 btn-lg btn-block" %>
            <% end %>
          </div>

          <div class="links text-center">
            <%= link "Sign up for Chat App", to: Routes.registration_path(@conn, :new) %>
          </div>
        </div>
        <div class="col-lg-6 right">
          <div class="caption">
            <span>Photo by <a href="https://unsplash.com/@austindistel?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Austin Distel</a> on <a href="https://unsplash.com/collections/11447470/work-%2B-building?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>